name: sphere
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  url_launcher: ^6.0.9
  like_button: ^2.0.3
  carousel_slider: ^4.0.0
  twilio_flutter: ^0.3.0
  flutter_overboard: ^3.1.3
  iconsax: ^0.0.8
  http: ^1.2.1
  async: ^2.11.0
  get_it: ^7.3.0
  fluttertoast: ^8.0.8
  firebase_database: ^10.1.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  image_picker: ^1.0.7
  firebase_messaging: ^14.7.10
  sqflite: ^3.0.1
  path_provider: ^2.0.6
  geolocator: ^8.0.1




dependency_overrides:
  path_provider: ^2.0.6
  sqflite: ^2.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite:
    sdk: flutter
  path_provider:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/json/

#  assets:
#    - images/a_dot_burr.jpeg
#    - images/a_dot_ham.jpeg
#  fonts:
#    - family: Schyler
#      fonts:
#        - asset: fonts/Schyler-Regular.ttf
#        - asset: fonts/Schyler-Italic.ttf
#          style: italic
#    - family: Trajan Pro
#      fonts:
#        - asset: fonts/TrajanPro.ttf
#        - asset: fonts/TrajanPro_Bold.ttf
#          weight: 700